name: Marc-Andre Seguin
favicon: null
layout_spectrum: 0.36059
typography_spectrum: 0.66682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#700018'
    - '#c57b00'
    - '#d49d4e'
    - '#a76571'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.45270482799969614
  rhythmicContrast: 0.19067921210080385
purpose: []
