name: Marc-Andre Seguin
favicon: null
layout_spectrum: 0.13922610157169402
typography_spectrum: 0.2551652661059052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5312940424773842
  lightness: 0.16004057764075696
  saturation: 0.45270482799969614
  rhythmicContrast: 0.19067921210080385
purpose: []
